# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-launchergrid-advanced-patch

# >> macros
BuildArch: noarch
# << macros

Summary:    Launcher grid advanced patch
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   lipstick-jolla-home-qt5 >= 0.22.44.7

%description
Launcher grid advanced patch


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-launchergrid-advanced-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-launchergrid-advanced-patch
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-launchergrid-advanced-patch
# >> files
# << files
